- id: '1544380776330'
  alias: scene_stua_dag
  trigger: []
  condition: []
  action:
  - data:
      entity_id: scene.stua_dag
    service: scene.turn_on
  - data:
      entity_id: input_boolean.hue_scene_stua_dag
    service: input_boolean.turn_on
  - data:
      entity_id: input_boolean.hue_scene_stua_kveld
    service: input_boolean.turn_off
  - data:
      entity_id: input_boolean.hue_scene_stua_film
    service: input_boolean.turn_off
  - data:
      entity_id: input_boolean.hue_scene_stua_alt_av
    service: input_boolean.turn_off
- id: '1544382573200'
  alias: scene_stua_kveld
  trigger: []
  condition: []
  action:
  - data:
      entity_id: scene.stua_kveld
    service: scene.turn_on
  - data:
      entity_id: input_boolean.hue_scene_stua_dag
    service: input_boolean.turn_off
  - data:
      entity_id: input_boolean.hue_scene_stua_kveld
    service: input_boolean.turn_on
  - data:
      entity_id: input_boolean.hue_scene_stua_film
    service: input_boolean.turn_off
  - data:
      entity_id: input_boolean.hue_scene_stua_alt_av
    service: input_boolean.turn_off
- id: '1544382586253'
  alias: scene_stua_film
  trigger: []
  condition: []
  action:
  - data:
      entity_id: scene.stua_film
    service: scene.turn_on
  - data:
      entity_id: input_boolean.hue_scene_stua_dag
    service: input_boolean.turn_off
  - data:
      entity_id: input_boolean.hue_scene_stua_kveld
    service: input_boolean.turn_off
  - data:
      entity_id: input_boolean.hue_scene_stua_film
    service: input_boolean.turn_on
  - data:
      entity_id: input_boolean.hue_scene_stua_alt_av
    service: input_boolean.turn_off
- id: '1544381642691'
  alias: scene_stua_alt_av
  trigger: []
  condition: []
  action:
  - data:
      entity_id: scene.stua_alt_av
    service: scene.turn_on
  - data:
      entity_id: input_boolean.hue_scene_stua_dag
    service: input_boolean.turn_off
  - data:
      entity_id: input_boolean.hue_scene_stua_kveld
    service: input_boolean.turn_off
  - data:
      entity_id: input_boolean.hue_scene_stua_film
    service: input_boolean.turn_off
  - data:
      entity_id: input_boolean.hue_scene_stua_alt_av
    service: input_boolean.turn_on


# Stua tidstriggere
- id: '1546162495905'
  alias: 'Rom=Stua, Tid=22:25, Scene=alt_av, Dager=Ukedager'
  trigger:
  - at: '22:25:00'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - sun
  action:
  - data:
      entity_id: automation.scene_stua_alt_av
    service: automation.trigger
- id: '1546163137757'
  alias: 'Rom=Stua, Tid=01:00, Scene=alt_av, Dager=Helg'
  trigger:
  - at: 01:00:00
    platform: time
  condition:
  - condition: time
    weekday:
    - fri
    - sat
  action:
  - data:
      entity_id: automation.scene_stua_alt_av
    service: automation.trigger
- id: '1546163068281'
  alias: 'Rom=Stua, Tid=16:15, Scene=dag, Dager=Alle'
  trigger:
  - at: '16:15:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: automation.scene_stua_dag
    service: automation.trigger
- id: '1546167116060'
  alias: 'Rom=Stua, Tid=19:00, Scene=kveld, Dager=Alle'
  trigger:
  - at: '19:00:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: automation.scene_stua_kveld
    service: automation.trigger