# Stua
- name: stua_dag
  entities:
    light.stua_stalampe_sofa:
      state: on
      brightness: 254
      rgb_color: [255,207,120]
    light.stua_stalampe_tv:
      state: on
      brightness: 254
      rgb_color: [255,207,120]
    light.stua_tv_leddstripe: off

- name: stua_kveld
  entities:
    light.stua_stalampe_sofa:
      state: on
      brightness: 178
      rgb_color: [255,207,121]
    light.stua_stalampe_tv:
      state: on
      brightness: 178
      rgb_color: [255,207,120]
    light.stua_tv_leddstripe:
      state: on
      brightness: 127
      rgb_color: [255,190,129]

- name: stua_film
  entities:
    light.stua_stalampe_sofa:
      state: on
      brightness: 127
      rgb_color: [255,165,76]
    light.stua_stalampe_tv:
      state: on
      brightness: 127
      rgb_color: [255,165,76]
    light.stua_tv_leddstripe:
      state: on
      brightness: 153
      rgb_color: [255,160,71]

- name: stua_alt_av
  entities:
    light.stua_stalampe_sofa: off
    light.stua_stalampe_tv: off
    light.stua_tv_leddstripe: off