# Gjennomsnittstemperatur
ute_average_temperature:
  friendly_name: 'Gjennomsnittstemperatur i rom'
  value_template: >-
      {{ ((float(states('sensor.utebod_sensor_temperature'))) / 1) | round(2) }}
  unit_of_measurement: °C

inne_average_temperature:
  friendly_name: 'Gjennomsnittstemperatur'
  value_template: >-
      {{ ((
              float(states('sensor.gangen_sensor_temperature'))
            + float(states('sensor.boden_sensor_temperature'))
            + float(states('sensor.soverommet_sensor_temperature'))
           )  / 3) | round(2)
      }}
  unit_of_measurement: °C

# Lysstatus
ute_number_of_lights_on:
  friendly_name: 'Antall områder med lys på'
  value_template: >-
    {% set total = 0 %}
    {% if is_state('light.utebod', 'on') %}
      {% set total = total + 1 %}
    {% endif %}
    {% if is_state('light.utelys', 'on') %}
      {% set total = total + 1 %}
    {% endif %}
    {{total}}

inne_number_of_lights_on:
  friendly_name: 'Antall rom med lys på'
  value_template: >-
    {% set total = 0 %}
    {% if is_state('group.ha_gang', 'on') %}
      {% set total = total + 1 %}
    {% endif %}
    {% if is_state('group.ha_innebod', 'on') %}
      {% set total = total + 1 %}
    {% endif %}
    {% if is_state('group.ha_soverommet', 'on') %}
      {% set total = total + 1 %}
    {% endif %}
    {% if is_state('group.ha_stua', 'on') %}
      {% set total = total + 1 %}
    {% endif %}
    {{total}}