utebod_sensor:
  friendly_name: 'Sensor'
  value_template: >-
    {% if is_state('binary_sensor.utebod_sensor_motion', 'on') %}
      Bevegelse registrert
    {% else %}
      Ingen bevegelse registrert
    {% endif %}

gangen_sensor:
  friendly_name: 'Sensor'
  value_template: >-
    {% if is_state('binary_sensor.gangen_sensor_motion', 'on') %}
      Bevegelse registrert
    {% else %}
      Ingen bevegelse registrert
    {% endif %}

boden_sensor:
  friendly_name: 'Sensor'
  value_template: >-
    {% if is_state('binary_sensor.boden_sensor_motion', 'on') %}
      Bevegelse registrert
    {% else %}
      Ingen bevegelse registrert
    {% endif %}

soverommet_sensor:
  friendly_name: 'Sensor'
  value_template: >-
    {% if is_state('binary_sensor.soverommet_sensor_motion', 'on') %}
      Bevegelse registrert
    {% else %}
      Ingen bevegelse registrert
    {% endif %}