tibber_grid_company:
  friendly_name: 'Netteier'
  icon_template: 'mdi:fuse'
  value_template: >-
    {{ state_attr('sensor.electricity_price_dyretrakket_18_e', 'grid_company') }}

tibber_eac:
  friendly_name: 'Estimert forbruk'
  icon_template: 'mdi:power-plug'
  unit_of_measurement: "kWh"
  value_template: >-
    {{ state_attr('sensor.electricity_price_dyretrakket_18_e', 'estimated_annual_consumption') }}

tibber_price_min:
  friendly_name: 'Minimumspris'
  icon_template: 'mdi:currency-usd'
  unit_of_measurement: "NOK/kWh"
  value_template: >-
    {{ state_attr('sensor.electricity_price_dyretrakket_18_e', 'min_price') }}

tibber_price_avg:
  friendly_name: 'Gjennomsnittspris'
  icon_template: 'mdi:currency-usd'
  unit_of_measurement: "NOK/kWh"
  value_template: >-
    {{ state_attr('sensor.electricity_price_dyretrakket_18_e', 'avg_price') }}

tibber_price_max:
  friendly_name: 'Maksimumspris'
  icon_template: 'mdi:currency-usd'
  unit_of_measurement: "NOK/kWh"
  value_template: >-
    {{ state_attr('sensor.electricity_price_dyretrakket_18_e', 'max_price') }}